glslc.exe base/base.vert                                        -o base/basevert.spv
glslc.exe base/base.frag                                        -o base/basefrag.spv
glslc.exe spotLightingPass/spotLighting.vert                    -o spotLightingPass/spotLightingVert.spv
glslc.exe spotLightingPass/spotLighting.frag                    -o spotLightingPass/spotLightingFrag.spv
glslc.exe spotLightingPass/scatteringSpotLighting.frag          -o spotLightingPass/scatteringSpotLightingFrag.spv
glslc.exe spotLightingPass/shadowSpotLighting.frag              -o spotLightingPass/shadowSpotLightingFrag.spv
glslc.exe spotLightingPass/scatteringShadowSpotLighting.frag    -o spotLightingPass/scatteringShadowSpotLightingFrag.spv
glslc.exe ambientLightingPass/ambientLighting.vert              -o ambientLightingPass/ambientLightingVert.spv
glslc.exe ambientLightingPass/ambientLighting.frag              -o ambientLightingPass/ambientLightingFrag.spv
glslc.exe shadow/shadowMapShader.vert                           -o shadow/shad.spv
glslc.exe customFilter/customFilter.vert                        -o customFilter/customFilterVert.spv
glslc.exe customFilter/customFilter.frag                        -o customFilter/customFilterFrag.spv
glslc.exe postProcessing/postProcessingShader.vert              -o postProcessing/postProcessingVert.spv
glslc.exe postProcessing/postProcessingShader.frag              -o postProcessing/postProcessingFrag.spv
glslc.exe skybox/skybox.vert                                    -o skybox/skyboxVert.spv
glslc.exe skybox/skybox.frag                                    -o skybox/skyboxFrag.spv
glslc.exe outlining/outlining.vert                              -o outlining/outliningVert.spv
glslc.exe outlining/outlining.frag                              -o outlining/outliningFrag.spv
glslc.exe sslr/SSLR.vert                                        -o sslr/sslrVert.spv
glslc.exe sslr/SSLR.frag                                        -o sslr/sslrFrag.spv
glslc.exe ssao/SSAO.vert                                        -o ssao/ssaoVert.spv
glslc.exe ssao/SSAO.frag                                        -o ssao/ssaoFrag.spv
glslc.exe layersCombiner/layersCombiner.vert                    -o layersCombiner/layersCombinerVert.spv
glslc.exe layersCombiner/layersCombiner.frag                    -o layersCombiner/layersCombinerFrag.spv
glslc.exe gaussianBlur/xBlur.vert                               -o gaussianBlur/xBlurVert.spv
glslc.exe gaussianBlur/xBlur.frag                               -o gaussianBlur/xBlurFrag.spv
glslc.exe gaussianBlur/yBlur.vert                               -o gaussianBlur/yBlurVert.spv
glslc.exe gaussianBlur/yBlur.frag                               -o gaussianBlur/yBlurFrag.spv

pause
