./glslc base/base.vert                                        -o ../spv/base/basevert.spv
./glslc base/base.frag                                        -o ../spv/base/basefrag.spv
./glslc spotLightingPass/spotLighting.vert                    -o ../spv/spotLightingPass/spotLightingVert.spv
./glslc spotLightingPass/spotLighting.frag                    -o ../spv/spotLightingPass/spotLightingFrag.spv
./glslc ambientLightingPass/ambientLighting.vert              -o ../spv/ambientLightingPass/ambientLightingVert.spv
./glslc ambientLightingPass/ambientLighting.frag              -o ../spv/ambientLightingPass/ambientLightingFrag.spv
./glslc shadow/shadowMapShader.vert                           -o ../spv/shadow/shad.spv
./glslc customFilter/customFilter.vert                        -o ../spv/customFilter/customFilterVert.spv
./glslc customFilter/customFilter.frag                        -o ../spv/customFilter/customFilterFrag.spv
./glslc postProcessing/postProcessingShader.vert              -o ../spv/postProcessing/postProcessingVert.spv
./glslc postProcessing/postProcessingShader.frag              -o ../spv/postProcessing/postProcessingFrag.spv
./glslc skybox/skybox.vert                                    -o ../spv/skybox/skyboxVert.spv
./glslc skybox/skybox.frag                                    -o ../spv/skybox/skyboxFrag.spv
./glslc outlining/outlining.vert                              -o ../spv/outlining/outliningVert.spv
./glslc outlining/outlining.frag                              -o ../spv/outlining/outliningFrag.spv
./glslc sslr/SSLR.vert                                        -o ../spv/sslr/sslrVert.spv
./glslc sslr/SSLR.frag                                        -o ../spv/sslr/sslrFrag.spv
./glslc ssao/SSAO.vert                                        -o ../spv/ssao/ssaoVert.spv
./glslc ssao/SSAO.frag                                        -o ../spv/ssao/ssaoFrag.spv
./glslc layersCombiner/layersCombiner.vert                    -o ../spv/layersCombiner/layersCombinerVert.spv
./glslc layersCombiner/layersCombiner.frag                    -o ../spv/layersCombiner/layersCombinerFrag.spv
./glslc gaussianBlur/xBlur.vert                               -o ../spv/gaussianBlur/xBlurVert.spv
./glslc gaussianBlur/xBlur.frag                               -o ../spv/gaussianBlur/xBlurFrag.spv
./glslc gaussianBlur/yBlur.vert                               -o ../spv/gaussianBlur/yBlurVert.spv
./glslc gaussianBlur/yBlur.frag                               -o ../spv/gaussianBlur/yBlurFrag.spv
./glslc linkable/deferredLinkable.vert                        -o ../spv/linkable/deferredLinkableVert.spv
./glslc linkable/deferredLinkable.frag                        -o ../spv/linkable/deferredLinkableFrag.spv
./glslc scattering/scattering.vert                            -o ../spv/scattering/scatteringVert.spv
./glslc scattering/scattering.frag                            -o ../spv/scattering/scatteringFrag.spv
./glslc boundingBox/boundingBox.vert                          -o ../spv/boundingBox/boundingBoxVert.spv
./glslc boundingBox/boundingBox.frag                          -o ../spv/boundingBox/boundingBoxFrag.spv
./glslc selector/selector.vert                                -o ../spv/selector/selectorVert.spv
./glslc selector/selector.frag                                -o ../spv/selector/selectorFrag.spv
./glslc bloom/bloom.vert                                      -o ../spv/bloom/bloomVert.spv
./glslc bloom/bloom.frag                                      -o ../spv/bloom/bloomFrag.spv
