glslc.exe base/base.vert				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/base/basevert.spv
glslc.exe base/base.frag				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/base/basefrag.spv
glslc.exe SpotLightingPass/SpotLighting.vert		    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/SpotLightingPass/SpotLightingVert.spv
glslc.exe SpotLightingPass/SpotLighting.frag		    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/SpotLightingPass/SpotLightingFrag.spv
glslc.exe SpotLightingPass/SpotLightingScattering.frag      -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/SpotLightingPass/SpotLightingScatteringFrag.spv
glslc.exe SpotLightingPass/SpotLightingAmbient.vert	    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/SpotLightingPass/AmbientSpotLightingVert.spv
glslc.exe SpotLightingPass/SpotLightingAmbient.frag	    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/SpotLightingPass/AmbientSpotLightingFrag.spv
glslc.exe shadow/shadowMapShader.vert                       -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/shadow/shad.spv
glslc.exe customFilter/customFilter.vert		    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/customFilter/customFilterVert.spv
glslc.exe customFilter/customFilter.frag		    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/customFilter/customFilterFrag.spv
glslc.exe postProcessing/firstPostProcessingShader.vert     -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/postProcessing/firstPostProcessingVert.spv
glslc.exe postProcessing/firstPostProcessingShader.frag     -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/postProcessing/firstPostProcessingFrag.spv
glslc.exe postProcessing/postProcessingShader.vert	    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/postProcessing/postProcessingVert.spv
glslc.exe postProcessing/postProcessingShader.frag	    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/postProcessing/postProcessingFrag.spv
glslc.exe bloom/bloom.vert				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/bloom/vertBloom.spv
glslc.exe bloom/bloom.frag				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/bloom/fragBloom.spv
glslc.exe oneColor/oneColor.vert			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/oneColor/oneColorVert.spv
glslc.exe oneColor/oneColor.frag			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/oneColor/oneColorFrag.spv
glslc.exe skybox/skybox.vert				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/skybox/skyboxVert.spv
glslc.exe skybox/skybox.frag				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/skybox/skyboxFrag.spv
glslc.exe stencil/firstStencil.vert			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/stencil/firststencilvert.spv
glslc.exe stencil/firstStencil.frag			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/stencil/firststencilfrag.spv
glslc.exe stencil/secondStencil.vert			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/stencil/secondstencilvert.spv
glslc.exe stencil/secondStencil.frag			    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/stencil/secondstencilfrag.spv
glslc.exe sslr/SSLR.vert				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/sslr/sslrVert.spv
glslc.exe sslr/SSLR.frag				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/sslr/sslrFrag.spv
glslc.exe ssao/SSAO.vert				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/ssao/ssaoVert.spv
glslc.exe ssao/SSAO.frag				    -o C:/Qt/repositories/build-vulkanCore-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/debug/core/graphics/shaders/ssao/ssaoFrag.spv

pause
