C:/VulkanSDK/1.2.170.0/Bin/glslc.exe base/base.vert				    -o base/basevert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe base/base.frag				    -o base/basefrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe SpotLightingPass/SpotLighting.vert		    -o SpotLightingPass/SpotLightingVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe SpotLightingPass/SpotLighting.frag		    -o SpotLightingPass/SpotLightingFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe SpotLightingPass/SpotLightingScattering.frag   -o SpotLightingPass/SpotLightingScatteringFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe SpotLightingPass/SpotLightingAmbient.vert	    -o SpotLightingPass/AmbientSpotLightingVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe SpotLightingPass/SpotLightingAmbient.frag	    -o SpotLightingPass/AmbientSpotLightingFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe shadow/shadowMapShader.vert		    -o shadow/shad.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe customFilter/customFilter.vert		    -o customFilter/customFilterVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe customFilter/customFilter.frag		    -o customFilter/customFilterFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe postProcessing/firstPostProcessingShader.vert  -o postProcessing/firstPostProcessingVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe postProcessing/firstPostProcessingShader.frag  -o postProcessing/firstPostProcessingFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe postProcessing/postProcessingShader.vert	    -o postProcessing/postProcessingVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe postProcessing/postProcessingShader.frag	    -o postProcessing/postProcessingFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe bloom/bloom.vert				    -o bloom/vertBloom.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe bloom/bloom.frag				    -o bloom/fragBloom.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe oneColor/oneColor.vert			    -o oneColor/oneColorVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe oneColor/oneColor.frag			    -o oneColor/oneColorFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe skybox/skybox.vert				    -o skybox/skyboxVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe skybox/skybox.frag				    -o skybox/skyboxFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe stencil/firstStencil.vert			    -o stencil/firststencilvert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe stencil/firstStencil.frag			    -o stencil/firststencilfrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe stencil/secondStencil.vert			    -o stencil/secondstencilvert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe stencil/secondStencil.frag			    -o stencil/secondstencilfrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe sslr/SSLR.vert				    -o sslr/sslrVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe sslr/SSLR.frag				    -o sslr/sslrFrag.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe ssao/SSAO.vert				    -o ssao/ssaoVert.spv
C:/VulkanSDK/1.2.170.0/Bin/glslc.exe ssao/SSAO.frag				    -o ssao/ssaoFrag.spv

pause
